apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/braydencw1/The_One
    path: apps/go-app
    targetRevision: main
    plugin:
      name: ksops
  destination:
    server: https://kubernetes.default.svc
    namespace: go-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
